### ISSUE TITLE
No way to add shortened options (e.g. '-R/--recursive')

### ISSUE THREAD

**Issue by alexpilk** [google/python-fire#108]
Would it be possible to create short names for default boolean arguments?

For example, if you have the following function:
```python
def hello(greeting, uppercase=False):
    greeting = greeting.upper() if uppercase else greeting
    print(greeting)
```

It would be nice to have the following usages:
`python hello.py Hey! -u`  
`python hello.py Hey! --uppercase`

**Comment by sdiepend** [comment]
This would indeed be a nice feature.

**Comment by Ralph-Wang** [comment]
It would be a great feature.
but I'm concerned about the conflict of the first letter

**Comment by alexshadley** [comment]
To deal with the issue of multiple args with the same letter, we could print a warning if a user attempts to use an ambiguous shortcut, i.e. one that could refer to multiple args.

I can go ahead and take a crack at this one!

**Comment by dbieber** [comment]
Thanks for your implementation! Will respond more fully later. :)
I see you already closed your own pull request -- why is that?

**Comment by alexshadley** [comment]
No problem!  While my code worked properly in Python 3.6, the Travis build failed for 2.7, 3.4, and 3.5.  I was going to re-open the pull once I'd worked those issues out.  By the way, how do you typically test compatibility across python versions?

**Comment by dbieber** [comment]
Locally I test different python versions with virtualenvs and the commands listed in the travis file.
I have one virtualenv for Python 2 and one for Python 3 (rather than one for each of the four supported Python versions.)  `python -m pytest` and `pylint fire --ignore=test_components_py3.py,parser_fuzz_test.py`

I don't run these multi-version tests locally often though, and instead I usually rely on travis and/or the google-internal testing and presubmit system for more thorough testing of multiple versions.

The output from travis for your PR is here:
https://travis-ci.org/google/python-fire/builds/429276689?utm_source=github_status&utm_medium=notification

It looks like the failures are just linter failures (two line-too-long errors). The reason 3.6 passed and the others fail is that we don't run the linter for 3.6, whereas we do for the other versions.

**Comment by alexshadley** [comment]
Thanks for the detailed respone.  Had some time to fix up the linting errors, pull request is reopened.  Let me know what you think!

**Comment by dbieber** [comment]
@alexshadley's initial implementation is checked in now.

Some next steps before this issue is done:

- raise a FireError if the arg doesn't match any keyword
- give exact matches priority (e.g. if there are args named "a" and "apple" then -a should match "a", rather than being flagged as ambiguous)
- support equal signs with single-character args (-a=10 should be OK)

**Comment by dbieber** [comment]
> - raise a FireError if the arg doesn't match any keyword

I was wrong about that being needed.

> - give exact matches priority (e.g. if there are args named "a" and "apple" then -a should match "a", rather than being flagged as ambiguous)
> - support equal signs with single-character args (-a=10 should be OK)

Done and Done

Thank you again Alex for the fix and tests!

**Comment by dbieber** [comment]
I should mention here that there is still not support for using a capital letter (-R) as a shortcut for a lowercase argument (e.g. recursive). You have to keep the same case currently (-r).

**Comment by pranavgupta1234** [comment]
Hey @dbieber what if do a smallcase version of the single letter we are getting and then check its matching among possible arguments ? Can we support the capital letter as well ?
