### ISSUE TITLE
Convert output to status code

### ISSUE THREAD

**Issue by robertvazan** [google/python-fire#158]
Fire script can be used in a shell script condition by comparing its output to `True`. It would be better to allow direct use by returning an exit code. Fire could convert every boolean output to status code by default. Or there could be an extra `--status` parameter that will test whether the output is true according to Python rules and set exit code appropriately. That would be more general, because it would allow for testing whether lists, for example, are non-empty.

Output could be suppressed in this case or there could be a separate `--quiet` option that silences all output.

Both of these options can be implemented by the application, but it would be nice to have them in fire since they can be applied to just about every command.

**Comment by robertvazan** [comment]
On the other hand, the convention of converting booleans to exit status is pretty easy to implement by passing custom wrapper to `fire.Fire()`.

```python
def wrap(module):
	def decorate(func):
		def call(*args, **kwargs):
			result = func(*args, **kwargs)
			if isinstance(result, bool):
				raise SystemExit(0 if result else 1)
			return result
		return call
	return dict((n, decorate(v)) for n, v in module.items() if callable(v))

if __name__ == '__main__':
	fire.Fire(wrap(globals()))
```

**Comment by robertvazan** [comment]
Actually, adding a wrapper is not that easy due to #159.

**Comment by dbieber** [comment]
A Fire CLI will exit with a status code of 0 if successful, and with a status code of 2 if it encounters a FireError (an error in usage made by the user of the CLI.)

If there is a Python error in the CLI code, then Python exits with a status code of 1 as usual (out of Fire's control).

If you want to change this (e.g. to choose a status code in response to the value returned by Fire), you are free to do so in your CLI code. It is actually just one line to do, e.g.:

```
if __name__ == '__main__':
  result = fire.Fire(anything)
  raise SystemExit(0 if result else 1)
```

**Comment by robertvazan** [comment]
`SystemExit` exception is the workaround I am using right now. It would still be nice to have Fire convert booleans to exit code since there's little point in returning True/False output to a shell script. Or just add `--status` to the list of generic options.

**Comment by dbieber** [comment]
It's a good idea, but I think it's better for the (default) exit code to indicate whether the command was successful, rather than the result of the command. After all, that's what exit codes usually mean (https://www.tldp.org/LDP/abs/html/exit-status.html).

As an example of why this is useful:
Today, Fire gives a status code zero if the command completes successfully. There are examples of times when a command returns `False` even though it's completed successfully. E.g., there is a Fire CLI with a command that determines whether there are any elements in a remote queue, and returns True or False. The status code is used to indicate whether that query was successful (e.g. it might timeout), while the output indicates what the result of the query is.

**Comment by robertvazan** [comment]
I am not going to pursue this further, because the project where this was relevant was meantime converted to nearly pure Python and the shell interface is now used mostly by humans rather than scripts. The `--status` flag would still be nice, but strictly speaking it's a different feature from what this issue originally suggested.
