### ISSUE TITLE
Help text uses class docstring instead of repr(object) in fire>=0.2.0 for objects in dict

### ISSUE THREAD

**Issue by fedorbirjukov** [google/python-fire#197]
dict with string values produces this CLI.

```
> python -c "import fire; fire.Fire({'key1': 'value1', 'key2': 'value2'})"
key1: value1
key2: value2
```

dict with object values produced a very simlarly CLI in fire==0.1.3.

```
key1: Value(name='value1')
key2: Value(name='value2')
```

Since fire>=0.2.0 this is not the case anymore...

```
> python value.py
NAME
    value.py

SYNOPSIS
    value.py GROUP

GROUPS
    GROUP is one of the following:

     key1
       Docstring

     key2
       Docstring
```

Could you restore the old behavior?

**value.py**

```
class Value:
    """Docstring"""
    def __init__(self, name):
        self.name = name
    def __repr__(self):
        return "%s(name=%r)" % (self.__class__.__name__, self.name)

import fire
fire.Fire({'key1': Value('value1'), 'key2': Value('value2')})
```

**Comment by dbieber** [comment]
Thanks for the feedback.

This is where we choose between the old behavior and new behavior:
1. If this condition is met, we use the old behavior:
https://github.com/google/python-fire/blob/8d372e2a67d1ad8135eca074629b52ddbca96f25/fire/core.py#L261-L262

2. Otherwise we use the new behavior:
https://github.com/google/python-fire/blob/8d372e2a67d1ad8135eca074629b52ddbca96f25/fire/core.py#L268-L272

While we're not going to completely revert to the old behavior, perhaps we could expand the set of conditions on which the old behavior gets triggered.

Specifically I propose that we broaden the definition of "SimpleGroup". Here's the current definition:

https://github.com/google/python-fire/blob/8d372e2a67d1ad8135eca074629b52ddbca96f25/fire/value_types.py#L43-L59

It uses IsValue:

https://github.com/google/python-fire/blob/8d372e2a67d1ad8135eca074629b52ddbca96f25/fire/value_types.py#L39-L40

We could modify IsValue to include objects for which the str method has been overridden.
If we were to do this, you would then need to modify your code as follows:

```
class Value:
    """Docstring"""
    def __init__(self, name):
        self.name = name
    def __repr__(self):
        return "%s(name=%r)" % (self.__class__.__name__, self.name)
    def __str__(self):
        return repr(self)

import fire
fire.Fire({'key1': Value('value1'), 'key2': Value('value2')})
```

but then it would work.

We'll have to consider what other implications this would have before we make the change, but my suspicion is that this would be a good change to make.

**Comment by dbieber** [comment]
Thanks for opening the PR @jaredtrog! I'll take a look.

**Comment by dbieber** [comment]
In the next release, objects defining a custom \_\_str\_\_ method can be included in dicts and the dicts will still be printed rather than shown in a full help screen.
