### ISSUE TITLE
should return error code on invalid parameters

### ISSUE THREAD

**Issue by madoke** [google/python-fire#22]
When firing a fire created command with invalid parameters, the return code is always 0. Shouldn't this return an error code ?

**Comment by akshaysharma096** [comment]
@madoke can you give an example?

**Comment by madoke** [comment]
Sure. Usually unix commands return `0` only if the program executed successfully consider `rm` for example. On a successful execution we would get `0` as the return code:
```bash
[00:44:12 madoke test]$ rm afile
[00:44:18 madoke test]$ echo $?
0
```
But if we call it with the wrong parameters (missing filename), we get a different return code (`64` in this case)
```bash
[00:44:04 madoke test]$ rm
usage: rm [-f | -i] [-dPRrvW] file ...
       unlink file
[00:44:07 madoke test]$ echo $?
64
```
Now Consider this simple python program:
```python
import fire

def test(param1, param2):
    print param1
    print param2

if __name__ == '__main__':
  fire.Fire(test)
```
When we invoke it correctly, all is good, we get a `0` return code
```bash
[00:48:54 madoke test]$ python test.py param1 param2
param1
param2
[00:34:56 madoke test]$ echo $?
0
```
But when we call it with the wrong parameters, we also get `0`
```bash
[00:49:24 madoke test]$ python test.py
Fire trace:
1. Initial component
2. ('The function received no value for the required argument:', 'param1')

Type:        function
String form: <function test at 0x10cb7c410>
File:        ~/Desktop/test/test.py
Line:        3

Usage:       test.py PARAM1 PARAM2
             test.py --param1 PARAM1 --param2 PARAM2
[00:33:26 madoke test]$ echo $?
0
```
In a situation like this, i would expect something different than `0`, which would enable me to conclude that the command failed. Several systems rely on the return codes to make decisions. In my case it's a jenkins job that will print success, even when i pass wrong parameters, but it could be for example a common pattern in bash scripts:
```bash
if [ $? -eq 0 ]; then
    echo OK
else
    echo FAIL
fi
```

Sorry that was too much text 🐙

**Comment by dbieber** [comment]
You make an interesting point.

In the normal case, where the entire main consists of running Fire, I agree with you that a proper status code would be good. However, Fire can (though not recommended) also be used in the middle of a program. Currently it returns the result of the Fire command, or None in the case of an error. Going forward we'll want to change this, e.g. so that the error is surfaced to the client code. Perhaps we'll want to return an object that contains the result, the fire trace, and the error if there is one. This would allow the client program to exit with a proper return code if they choose to, but it would have to be an explicit choice by the client.

**Comment by pmartindev** [comment]
This seems to me like an appropriate feature. The fire command did execute correctly, and it returned the proper exit code for itself. This library is a powerful tool in a CI/CD pipeline, and I would agree that a feature that would allow the client exit code to be surfaced would be very beneficial in these scenarios. Would a command line argument that, when passed, propagates the client exit code to Fire suffice?

**Comment by madoke** [comment]
@dbieber makes sense. That way you could also have different return codes for different commands. Following that, i was able to find a simple work around. It feels a little hackish but it does what i need:
```python
import fire
import sys

def test(param1, param2):
    print param1
    print param2
    return True

if __name__ == '__main__':
  result = fire.Fire(test)
  if result is None:
    sys.exit(1)
```
I guess this is pretty much the idea of the return object, but it just compares the result against none. It will fail in some other cases like `--help` for example.

**Comment by madoke** [comment]
@pmartindev didn't quite get it, could you provide an example or two ?

**Comment by dbieber** [comment]
Yeah @madoke, your workaround is exactly what I had in mind. One problem with it is that fire.Fire will return None if `test` returns None, and there's currently no way to distinguish between a None that indicates an error and a None that just means None was returned (and, as you point out, other cases like `--help`).

**Comment by pmartindev** [comment]
@madoke My idea would be to have command line argument along the lines of --pass-thru (similar to Powershell's -PassThru paramater) that would allow the stdout/stderr/exit code of the function Fire is executing to be either output as an object (similar to what @dbieber suggested) or surface it through Fire's stdout/stderr/exit code.

**Comment by jtratner** [comment]
What about making a small backwards-incompatible change and going the reverse direction - defaulting to raising `SystemExit` unless some keyword arg is passed? (or adding some `ChainableFire` object instead).
 
That would also help with things like the exit of zero on `python mycommand.py -- --help`

I guess there's some ambiguity in what constitutes a successful exit (just no exception? Ended up with a string?) but I think defaulting to non-zero exit codes on exceptions would help make fire more usable

**Comment by dbieber** [comment]
I don't think adding a flag is appropriate here. If Fire provides a choice (sys.exit vs return) then it should provide that choice to the client code calling Fire, not to the end user. The end user won't have context as to whether it makes sense for the program to keep running after the call to Fire or not.

When Fire hits a usage error the options are:
1. Display the error and then exit w/ a status code.
2. Display the error and return the error (wrapped in some object) to the client.
3. Display the error and raise the error to the client.

The downside of 1 is that it provides the client no way of handling the error.
The downside of 2 is that the default use case (just calling fire.Fire) doesn't get proper status codes.
The downside of 3 is that the default use case (just calling fire.Fire) will show a Python trace in the case of a usage error, which isn't the user experience we want.

I lean toward option 2 because it makes getting proper status codes a simple 1-liner for people who want it (Something like `result = fire.Fire(); result.ExitIfError()`; exact syntax tbd.) and also allows the client the flexibility to handle the result of fire (error or not) however they chose. Option 1, while it gets status codes right, provides no way for people to handle usage errors themselves.

**Comment by jtratner** [comment]
That seems like a reasonable way to do it, but I'd love it if the golden
path raised system exit by default so that the one-liner "does what you
expect". How about fire.Fire(exit_if_error=False) ? (With the keyword
argument defaulting to True) that way you don't have to do anything special
(and if you want to do complex chaining then you are probably going to read
the docs more in-depth)

**Comment by dbieber** [comment]
1.  I just found out you can catch sys.exit calls with `except SystemExit`. Maybe there's a way to have Fire raise a SystemExit error that includes the fire-specific information, thereby giving status codes in the default case while still allowing the client to catch and examine the error information if they choose.

2. Currently `Fire` has 0 documented keyword arguments (and 2 undocumented keyword args that you shouldn't rely on, since they might change or be removed). So, I would be hesitant to add a keyword argument at this point for a small feature like this. [That said, there are things for which it will be appropriate to add keyword args in the future (e.g. you should be able to directly pass argv to Fire rather than having it use sys.argv), and we'll have to think through these carefully in order to keep a clean API going forward.]

**Comment by jtratner** [comment]
I like the idea of custom SystemExit class - I think that's a nice way of
handling it 👍

**Comment by dbieber** [comment]
👍 Looks like something like this will do the trick.

```
class FireExit(SystemExit):
  def __init__(self, status, trace):
    super(FireExit, self).__init__(status)
    self.trace = trace
```

Very tempting to call the exception 'FireEscape' :).

**Comment by jtratner** [comment]
Yep - agreed - and trace not the result object itself?

Also I'd be interested to dig in and put this together if you're down for
some help :)

**Comment by dbieber** [comment]
Would certainly appreciate the help. I did a first pass so I'll get that on a branch for us to work off of.

Regarding trace vs the result, there is no result in the case of an error :). That said, FireTrace does need some clean up.

**Comment by dbieber** [comment]
First pass is here https://github.com/google/python-fire/compare/z2017-03-21-fire-exit
