### ISSUE TITLE
CONTRIBUTING.md could have more detail

### ISSUE THREAD

**Issue by MichaelCG8** [google/python-fire#252]
Extra detail could be added to CONTRIBUTING.md so that new contributors will be aware of the process and coding style.  Some suggestions:
- The preferred flow is that contributors fork the project and open a pull request from there, rather than creating a branch.
- Code style should follow the [Google Python Style Guide]
- Use an indentation of 2 spaces for blocks, and 4 spaces for line continuation.
- Use PascalCase for function and method names.
- Use parentheses around return tuples (this is notably a divergence from the Google guide, and may be changed).
- Do not use [PEP 484] style type hints, to preserve compatibility with Python versions < 3.5
- Use single quotes around strings, and three double quotes around docstrings.
- Run tests by installing pytest, mock, termcolor, and hypothesis, then opening a bash terminal in the root of the repository and running `pytest`.
  - Do this with both a Python 2 and 3 interpreter, the more versions the better.
- Lint your code by installing pylint, opening a bash terminal in the root of the repository and running `pylint fire`.  Ensure that the new code is not flagged up.
  - Do this with both a Python 2 and 3 interpreter.

[Google Python Style Guide]: http://google.github.io/styleguide/pyguide.html
[PEP 484]: https://www.python.org/dev/peps/pep-0484

I am happy to take on this task once there has been some discussion.
- What other detail would be useful?
- Is there a continuous integration process that makes the suggestion to test with multiply Python versions redundant?

Cheers,
Michael

**Comment by dbieber** [comment]
Thanks MichaelCH8! This looks great.

> Use parentheses around return tuples.

We should fix the parentheses around return tuples in the code.

> Is there a continuous integration process that makes the suggestion to test with multiply Python versions redundant?

We are using Travis for CI. It is configured to run on PRs and commits to master. You can see the results (passing) on your PR by clicking the green check or red x.

---

A few other FYIs. The codebase internally at Google has slightly different lint rules from those tested in CI. I don't have the full list of differences handy. One that you didn't list (might be tested by CI though) is an 80 char line limit.

As a result of these differences, we've been making an effort lately to avoid asking contributors to fix all style issues (especially those that CI doesn't catch) and instead we clean up the PR as part of merging it, since we're able to run the internal checks at that point.

Ideally we'd configure Travis to match the internal checks exactly.

**Comment by MichaelCG8** [comment]
Okay, I'll remove the parentheses line then.
To avoid putting too much onus on contributors, I'll mention that Travis is used, but it is suggested to run the tests with at least one interpreter 
Likewise for linting I'll change to just one interpreter.

**Comment by dbieber** [comment]
Done with #253 by 629d91c3f3656049f61b44b734044e51a7895619
