### ISSUE TITLE
fire.Fire() ruins fire.Fire(fire.Fire)

### ISSUE THREAD

**Issue by ubershmekel** [google/python-fire#3]
Hi python-fire,

`fire.Fire` looked like a very interesting function so I wanted to inspect it with `fire.Fire`. I was surprised that the interpreter printed out a dictionary with all my locals and globals.

I'm not sure if that's what you guys intended to happen, I guess it kind of is because of `fire.Fire()` defined as a valid invocation which means `fire.Fire(globals() + locals())`. Perhaps it's worth considering introducing a different function that would do that? `fire.FireThisModule()`?

**Comment by dbieber** [comment]
You can certainly inspect the Fire function with Fire!

To inspect a function without calling it, and '-- --help' to your command. Without that, the function will get called. And as you noticed, when Fire is called with no arguments, it spits out all your locals and globals.

**Comment by ubershmekel** [comment]
Why does a callable class not get called?
Compare the following:

```
import fire
from __future__ import print_function

lamb = lambda: print(123)

class CallableClass:
    def __call__(self):
        print(123)

def function():
    print(123)

def arity(x, y):
    print(123)

fire.Fire(lamb)
fire.Fire(CallableClass) # note `inspect.getsourcefile` throws when this is used in the interpreter
fire.Fire(CallableClass())
fire.Fire(function)
fire.Fire(arity)
fire.Fire()
```

Unrelated rant: I personally feel the zero-arity `function` shouldn't get called even when `--help` is used. I realize a function might have a `help` argument but I'd rather break that argument name than the expectation of every single command line app with no arguments (I commonly use `--help` by itself as I'm sure many other do based on the included warning). Sorry I'm kind of using this issue as a feedback post at this point.

**Comment by dbieber** [comment]
> Sorry I'm kind of using this issue as a feedback post at this point.

Not a problem.

> I personally feel the zero-arity function shouldn't get called even when --help is used.

Yes, largely I agree. Currently I'm leaning toward having --help behave the same as '-- --help' (e.g. preventing the final fn/class from being called/instantiated) except in the case where the fn accepts a help argument (either explicitly or via **kwargs). I want to as much as possible allow Fire to work on any Python component at all.

> Why does a callable class not get called?

This is because we currently only look for argspecs [on classes and routines](https://github.com/google/python-fire/blob/master/fire/core.py#L319), but not on other objects (in your example it's the instantiated object that is callable, not the class itself).
I am certainly open to changing this behavior. It's a nontrivial change and could introduce ambiguous commands, and so will require careful thought.

> fire.Fire(CallableClass) # note `inspect.getsourcefile` throws when this is used in the interpreter

Good catch. We should fix this.

**Comment by dbieber** [comment]
The getsourcefile issue is resolved now. 1239bdd23b0112701d3817d5fdf109f80ae4c35b

**Comment by 1445drewran** [comment]
hi how are you
