### ISSUE TITLE
Feature request short arguments in help text

### ISSUE THREAD

**Issue by ConorSheehan1** [google/python-fire#317]
Saw short arguments were added in #141, which looks great!
 
I was wondering if it'd be possible to include the short args in help text too?

I was thinking something like, given:
```python
# foo.py
import fire

def func(foo=False, bar='bar', baz='dupe'):
    pass

if __name__ == '__main__':
    fire.Fire(func)
```
The output could change like this:
```diff
# python foo.py --help
 FLAGS
-    --foo=FOO
+    -f, --foo=FOO
         Default: False
     --bar=BAR
         Default: 'bar'
     --baz=BAZ
         Default: 'dupe'
```
I'd be happy to try and pr this myself if you think it's worth adding?

**Comment by xiaoxstz** [comment]
**If a parameter has no default value, it will be listed in `POSITIONAL ARGUMENTS`, and has no short argument; Otherwise, it will be listed in `FLAGS`.**

**If a parameter is listed in `FLAGS`, and its first character is exclusive, its first character will be set as its short name.**

For example, save the script below to file `test.py`

```Python
import fire


def func(foo, bar='bar', baz='dupe',number=0):
    pass

if __name__ == '__main__':
    fire.Fire(func)
```

The help command `python test.py -h` outputs:

```txt
NAME
    test.py

SYNOPSIS
    test.py FOO <flags>

POSITIONAL ARGUMENTS
    FOO

FLAGS
    --bar=BAR
        Default: 'bar'
    --baz=BAZ
        Default: 'dupe'
    -n, --number=NUMBER
        Default: 0

NOTES
    You can also use flags syntax for POSITIONAL ARGUMENTS
```
