### ISSUE TITLE
**kwargs flags are completely ignored

### ISSUE THREAD

**Issue by jkbecker** [google/python-fire#321]
Hi,

I'm in the process of building a client-server application using Fire. My client has the capability of starting the server, and attaching to it. While building out the different options for doing so, I noticed that fire will not process any of my flags correctly! Here is a stripped-down minimally viable demonstrator (saved as `firetest.py`):

```python
import fire

class MyClient(object):
    """ Client that can start a server and attach to its output. """

    def __init__(self, version=None, **kwargs):
        pass

    def startserver(self, configfile, restart=False, attach=False, **kwargs):
        print('startserver:', restart, attach, kwargs)
        if attach:
            self.attach(**kwargs)

    def attach(self, *args, **kwargs):
        print('attach:', args, kwargs)

if __name__ == '__main__':
    fire.Fire(MyClient)
```

I am running the following test commands:
```bash
$ python3 firetest.py startserver test --restart=True --attach=True --channel=output
# expected output:
startserver True True {'channel': 'output'}
attach: () {'channel': 'output'}
# actual output:
startserver False False {}

$ python3 firetest.py attach --channel=[output,logs]
# expected output:
attach: () {'channel': ['output', 'logs']}
# actual output:

$ python3 firetest.py attach verbose --channel=output
# expected output:
attach: ('verbose',) {'channel': 'output'}
# actual output:
attach: ('verbose',) {}
```

Am I doing something fundamentally wrong here? The way it is behaving for me is completely useless, and as far as I can tell, wrong. I've been staring at this for way too long and created different variants of it, to no avail. Help? :pleading_face:

**Comment by dbieber** [comment]
Hi, the trouble is that the `__init__` function accepts **kwargs, so all your command line arguments are being consumed by `__init__`.

A few ways to resolve this. Any one of the following will fix your issue.

1. Initialize the class yourself. `fire.Fire(MyClient())`
2. Remove **kwargs from `__init__` (or remove `__init__` entirely since you're not using it!)
3. Use a separator (`-`) at the command line.
`python3 firetest.py - startserver test --restart=True --attach=True --channel=output`

When you put a separator (`-` by default) in a command, it indicates that you're done passing arguments to the current component (in this case, the MyClient _class_). All future arguments will be passed to future components (i.e. the MyClient _object_).

**Comment by jkbecker** [comment]
Ohh... That actually makes a lot of sense 🤦‍♂️ 
Thanks for the thorough diagnostic! Will check this tomorrow morning and close the ticket if all goes well. I'm actually using `__init__` in my real code, I just reduced it to a minimally viable example here, so I'll probably do 1. since the separator approach feels a bit clunky as a main way of running my CLI.
