### ISSUE TITLE
is autocomplete working??

### ISSUE THREAD

**Issue by ShivKJ** [google/python-fire#347]
Hi,

I am learning `Fire` and am interested in how `completion` works.

I created a script `main.py`

```python
import fire


def hello(name="World"):
    return "Hello %s!" % name


if __name__ == '__main__':
    fire.Fire(hello)

```

ran the following command,

```bash
python main.py -- --completion > completion

source completion
```

Now when I run `python main.py` and press \<TAB\> it does not seem provide cli parameter. 
Let me know if I am not using it correctly.

**Comment by paolodina** [comment]
I resolved creating a Python package. Then install, generate the completion script and worked.

**Comment by dbieber** [comment]
@ShivKJ When you run with `--completion` to generate the completion script, Fire uses the `name=` parameter to register completions for commands starting with that name. Your commands start with `python main.py` but the completions are probably registered just to `main.py`. It would be better if what you're doing _just worked_, but it doesn't. Alias `python main.py` to a name or make `main.py` executable (e.g. by running chmod +x main.py and adding a shebang line at the start) in order to use your script with tab completion.

Thanks for writing up your approach @paolodina -- that's really helpful.
