### ISSUE TITLE
What condition does fire use to decide if input is a tuple or a string

### ISSUE THREAD

**Issue by zyxue** [google/python-fire#356]
I'm playing with:

```python
from fire import Fire

def f(a):
    print(f'{type(a)=:}')
    print(f'{a=:}')

Fire(f)
```

and see

```
python toy.py -a x,y,z
```
returns a tuple
```
type(a)=<class 'tuple'>
a=('x', 'y', 'z')
```
But 
```
python toy.py -a a.txt,b.txt,c.txt
type(a)=<class 'str'>
a=a.txt,b.txt,c.txt
```
returns a string, which is kind of confusing.

Version:
```
>>> fire.__version__
'0.3.1'
```

**Comment by AlexeyShaferov** [comment]
I have exactly the same problem. How to make it always preserve a string? I do not need a tuple, regardless of the presence of a comma.

**Comment by Nic-Ma** [comment]
Hi @[dbieber](https://github.com/dbieber),

Thanks for the great project, very cool a CLI tool!
We are investigating to integrate it into the MONAI bundle: https://github.com/Project-MONAI/MONAI/issues/3482.
But we face the similar issue as we may have complicated args like: **id="AA#BB#<CC>"**
I think maybe that because `fire` uses `ast` to parse args and can't support complicated strings?
Is there any possible solution or workaround?

Thanks in advance.

**Comment by dbieber** [comment]
One thing that makes this confusing is that your shell (e.g. bash) strips quotes from the commands you run.
So if you run `example.py --arg="value1,value2"`, Fire doesn't see the quotes, it just sees `value1,value2`.

@Nic-Ma  is correct; we use ast to parse args.
1. If it sees things in quotes it will treat them as a string (but remember the quotes might have been stripped away by your shell)
2. If it sees a bare variable name, it will treat that as a string (but remember, variables names can't have spaces or hyphens or commas, just alphanumeric characters and underscore)
3. If it sees something it can't convert to another type, it will fall back as treating it as a string.


You can also use decorators.SetParseFns to force Fire to treat a value as a particular type / to change how its arguments get parsed.
