### ISSUE TITLE
Could or would python-fire be supported  or ported by snakeware-os?

### ISSUE THREAD

**Issue by codehangen** [google/python-fire#405]
Hi all. 

I would like to know if the open source python-fire project can be supported or ported by the snakeware linux distro. So... can python-fire be supported or ported by snakeware?

<br/>

*This question is not a feature request, but a question.*

**Comment by dbieber** [comment]
I'm not familiar with snakeware. It sounds like this may be a question for snakeware rather than a question for fire. What would be involved on fire's end to support this?

**Comment by dbieber** [comment]
I looked up snakeware. As I understand it, it's an operating system where you are booted directly into a Python interpreter. So if you want to call a Python function, you can import it and call it directly - no need for Fire for this use case. 
I don't know what snakeware does for CLI tools. Do they have a mechanism for saying a module should always be imported? If so, that would probably be the thing to do.

Of course, you definitely can use Fire on snakeware! Just import fire and run fire.Fire(your_object, your_command). This will dispatch the command to run on the object. It's just easier to issue the command directly rather than having fire do it.
