### ISSUE TITLE
Completions for fish shell

### ISSUE THREAD

**Issue by JelteF** [google/python-fire#56]
It would be really great to have completions generated for the fish shell: https://fishshell.com/docs/current/commands.html#complete

**Comment by dbieber** [comment]
Thanks @Ellmen for adding fish completion support. This will go out in the next release. No eta for this just yet.

**Comment by darrenburns** [comment]
Hi @dbieber, I notice that the fish completion support didn't go out in the latest release. Was this intentional? I found this repo and noted the fish completion support in the README on `master`, only to realise after trying to use it that there's no code in the latest release supporting this feature.

**Comment by dbieber** [comment]
We're overdue for a release at this point, aiming to finish the help text rewrite before releasing. Fish support should be included in the next release. Apologies for the delay.
