### ISSUE TITLE
Better handling of argument name typos

### ISSUE THREAD

**Issue by gerardlouw** [google/python-fire#84]
Using this minimal example of a Python-fire CLI:

```python
import fire

def f(my_arg):
    print(my_arg)

fire.Fire(my_arg)
```

This is the result I get:

```bash
➜  ~ python example.py --my-arg=hello
hello
➜  ~ python example.py --myarg=hello
--myarg=hello
```

As you can see, a typo in the argument leads to unexpected behaviour, which can be really hard to debug.

I would suggest never treating an argument matching `--[a-zA-Z0-9_-]+` as positional, without some sort of escaping by the user (perhaps similar to the escaping you require to avoid parsing ints, etc.).

**Comment by dbieber** [comment]
Thanks for this suggestion! It's a good idea, and I will let you know if we decide to go with this design change in a future version.

**Comment by dbieber** [comment]
@gerardlouw, would you be interested in making this improvement?

**Comment by gerardlouw** [comment]
Sure, I'd be happy to send a pull request. Could you point me to where in the code this should go? From a quick glance, it looks like https://github.com/google/python-fire/blob/e76a10c0511ea4485b57543ccb966e7778213279/fire/core.py#L663-L741 might be the right place.

**Comment by dbieber** [comment]
The call paths we're interested in are: (_Fire -> _CallCallable -> _MakeParseFn) and (_Fire -> CallCallable -> parse -> _ParseArgs).

The `parse` function is defined here (_ParseFn):
https://github.com/google/python-fire/blob/e76a10c0511ea4485b57543ccb966e7778213279/fire/core.py#L566-L567

In particular we're interested in the `else` block here:
https://github.com/google/python-fire/blob/e76a10c0511ea4485b57543ccb966e7778213279/fire/core.py#L638-L644

Line 644 is where we indiscriminately take one of the remaining args and treat it as a positional arg.
Instead, we should take the first arg that doesn't start with `--` and use that.

**Comment by greenmoon55** [comment]
Just for clarification, will we consider these variables for varargs?

**Comment by dbieber** [comment]
What do you think about the following?

If:
- an argument starts with '--'  (e.g. `--arg`)
- AND the argument is not surrounded in quotes (in practice this means being double surrounded in quotes :/) e.g. (`'"--arg"'`)
- AND the argument is not prefixed with an equal sign (e.g. `--someflag=--arg`)

Then:
- We shouldn't treat the arg as a string at all, since the user probably meant for the arg to be a flag, not a value.

**Comment by greenmoon55** [comment]
Thanks! Can I remove these arguments in '_ParseKeywordArgs' to avoid being assigned to varargs?

**Comment by dbieber** [comment]
Ack! I only just noticed your question now. Sorry for the delay.

Yes, handling these arguments in _ParseKeywordArgs sounds reasonable to me.
You could modify _ParseKeywordArgs to return `kwargs, remaining_args, unused_kwargs` instead of  `kwargs, remaining_args`, where unused_args is a list of any keyword args that weren't used.
By separating these unused keyword args from `remaining_args`, we prevent these args that were intended to be keyword args from accidentally being used as positional args.
Then, at the end of _ParseFn, we can add the unused_kwargs back into remaining_args, in case they're used later on in _Fire.

**Comment by dbieber** [comment]
Thanks for the contribution!

**Comment by greenmoon55** [comment]
Thanks for your help!
