### ISSUE TITLE
Calling fire on a class + a static function

### ISSUE THREAD

**Issue by cBournhonesque** [google/python-fire#89]
If I have a file examply.py:

```python

def function1(param = 3):

class A:
    def __init__(self, param = 1):
    def function2(self, param = 2):

if __name__ == '__main__':
    fire.Fire(...)
```

How can I expose both objects to Fire?
If Ido `fire.Fire(A)` and `fire.Fire(function1)`, then calling `python example.py --param=2` does not have a clear behavior. (does it call the function or the class?)
Even if the arguments did not have the same name, and I only called the argument of `function1`, would Fire automatically instantiate an object of class A even if only wanted to call the function function1?

Or is the only solution to call fire.Fire() to expose everything, and then to call
`python example.py function1 4`
`python example.py A function2 5` ?

**Comment by dbieber** [comment]
You have two main options:

1.
`fire.Fire()`
Then you can do `example.py function 1` or `example.py A function2 5` just like you suggested.
[You can also do `example.py A --param=5 function2 5` if you want to change the value of param in A's constructor.]

2.
```
fire.Fire({
  'function1': function1,
  'function2': A().function2,
})
```
Then you can do `example.py function1 4` or `example.py function2 5`, but you cannot change the value of param in A's constructor since you've hard-coded the call to the constructor.

----

There are various other ways to do this such as `A.function1 = function1; fire.Fire(A)` or `fire.Fire([function1, A])` or making a new class that exposes both an A and function1, but I think the above approaches (1+2) are better.
