### ISSUE TITLE
date string being parsed as integer math expression

### ISSUE THREAD

**Issue by slotrans** [google/python-fire#95]
Using fire 0.1.2...

$ python mycode.py my_function --daydate 2017-10-09 -> The daydate parameter of my_function is passed the string value '2017-10-09' as expected and desired.

$ python mycode.py my_function --daydate 2017-10-10 -> The daydate parameter of my function is passed the integer value 1997. Apparently '2017-10-10' is being parsed as an integer math expression? I'm not sure why anyone would ever want that, and I'm very sure that no one would expect that.

I understand that I can solve this by placing my argument value in both double and single quotes, but I'd really rather not have to do that.

**Comment by mbarkhau** [comment]
I have the same issue.

```python
import sys
import fire

def main(arg=""):
    print(sys.argv)
    print(arg, type(arg))

if __name__ == '__main__':
    fire.Fire(main)
```

```bash
$ python test_fire.py --arg "1+1"
['test_fire.py', '--arg', '1+1']
2 <class 'int'>

**Comment by dbieber** [comment]
Thanks for opening this Issue -- I agree this needs fixing.

Is it just BinOps, or is there something more general here we should do?
Maybe we should have a whitelist rather than a blacklist for parsing.
We (should) support numeric literals, string/unicode literals, and tuples, lists, and dicts (and sets, if it were doable) of things we support.
There shouldn't be any BinOps in there at all, even e.g. as a value inside a dict.

**Comment by mbarkhau** [comment]
Yes, a more general solution could be done, I just didn't want to deal with the whole ast parsing for now. The PR solves at least the minimal case where there is a top level expression.
